### ISSUE TITLE
Error running "pip install -Ur requirements.txt"

### ISSUE THREAD

**Issue by AngSupremo** [maxmohash/bart-etd-checker#1]
Hi! I'm new to Python and I was following the instructions but I got the error message in the photo.

![image](https://user-images.githubusercontent.com/32427364/31745233-bf83d22c-b416-11e7-9451-4c0e64b777d7.png)

At the very bottom it showed the error message too.

![image](https://user-images.githubusercontent.com/32427364/31745286-f414c0aa-b416-11e7-9b14-98d2568cdea5.png)

**Comment by maxmohash** [comment]
Is your system OS Ubuntu? If yes then follow the guidelines here https://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu and this is also helpful link http://lxml.de/installation.html

**Comment by AngSupremo** [comment]
Thanks for your reply.  I am using Raspbian.


________________________________
